# Spring Boot Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.ecoomerce.sportscenter: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sportscenter
    username: root
    password: password
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
